What could we predict the radio-to-optical link accuracy if we use current ICRF3 and Gaia DR2 solutions?

Here I make a simulation.

In [1]:
from astropy.table import join
import numpy as np
from numpy import sqrt, deg2rad

# My modules
from my_progs.catalog.read_icrf import read_icrf3
from my_progs.catalog.read_gaia import read_dr2_iers
from my_progs.catalog.vsh_analysis import covariance_analysis
from my_progs.catalog.pos_diff import radio_cat_diff_calc

In [2]:
icrf3sx = read_icrf3(wv="sx")
icrf3k = read_icrf3(wv="k")
icrf3xka = read_icrf3(wv="xka")

gdr2 = read_dr2_iers()

In [3]:
com1 = radio_cat_diff_calc(icrf3sx, gdr2, sou_name="iers_name")
com1

<Table length=2820>
iers_name       ra_err_1       ...       nor_dec             nor_sep      
                  mas          ...                                        
   str8         float64        ...       float64             float64      
--------- -------------------- ... -------------------- ------------------
 0000-197   0.2043727812594762 ...  0.18154164723418847   2.70320962823066
 0000-199   0.1321846666876117 ...     -4.4257899633162 5.2818243603952375
 0001+459  0.11585246722802883 ...   0.9030344496190486 1.3693305655846135
 0001-120  0.07282342412197838 ... -0.14351526779930124 3.5278552210909058
 0002+051  0.16441624418151832 ...   2.6055335533095847 2.6091860568754117
 0002+541  0.09605221846642922 ...  -1.2494698934271358 3.0609288794261396
 0002-170   0.1295244409667281 ...  -2.1572893131968782 2.2197696728495346
 0002-478  0.06624331361080132 ...  -0.5864398976027061 0.6146810169726248
 0003+123  0.10627813021774135 ...   1.8995944697104261 1.9305633787434655
      ...                  ... ...                  ...                ...
 2355-291  0.18215301718819626 ...    2.186813907193713 3.1750088485941816
 2355-534  0.03496351625011808 ...    0.717650073893479   4.78194185670016
 2356+196  0.07417827219346457 ...  -1.1848065096002034  4.570753985648204
 2356+385 0.030842247082975484 ...  -0.1870824834740687 1.7156393541934234
 2356+390  0.09577664080314209 ...  -0.6892686446804718 2.7268569025597946
 2356-069     0.12842693142195 ...  -0.6478781330200966 0.6753765895089889
 2357-318  0.03847108160117668 ...   0.8185284520154167  0.998862635472849
 2357-326   0.1018819152558419 ...   2.0965713101946055  35.70788441487609
 2358-161  0.10129550931840807 ...   2.7030703264508973 2.7030778481730002
 2359-221   0.1855389805384662 ...  -1.9756498420849966 3.6753725247744033

In [4]:
ra = deg2rad(np.array(com1["ra"]))
dec = deg2rad(np.array(com1["dec"]))

sig1, mat1 = covariance_analysis(com1["dra_err"], com1["ddec_err"], 
                                 ra, dec, 
                                 com1["dra_ddec_cov"], deg=1)

print(sig1)
print(mat1)

sig2, mat2 = covariance_analysis(com1["dra_err"], com1["ddec_err"], 
                                 ra, dec, 
                                 com1["dra_ddec_cov"], deg=2)

print(sig2)
print(mat2)

[0.00454001 0.00434206 0.00458253 0.00481269 0.00453321 0.00431681]
[[ 1.         -0.00745872 -0.02508901  0.01581301 -0.29735471  0.09615023]
 [-0.00745872  1.          0.00685353  0.28753324  0.00466684 -0.00370987]
 [-0.02508901  0.00685353  1.         -0.08203864 -0.03746342 -0.01383566]
 [ 0.01581301  0.28753324 -0.08203864  1.          0.04156129 -0.13870722]
 [-0.29735471  0.00466684 -0.03746342  0.04156129  1.         -0.16387021]
 [ 0.09615023 -0.00370987 -0.01383566 -0.13870722 -0.16387021  1.        ]]
[0.00491534 0.00471108 0.00494997 0.00510932 0.00478591 0.00451208
 0.00290686 0.00288013 0.00566141 0.00606059 0.00553811 0.00302972
 0.00306516 0.00586294 0.00593018 0.00507342]
[[ 1.00000000e+00 -5.18451398e-02  2.13737769e-02 -2.43991544e-02
  -3.10033144e-01  1.66349003e-01 -1.72716492e-02  1.33440976e-01
   2.29959569e-01 -2.02408219e-02 -4.08773371e-02 -1.51886012e-01
  -1.31427300e-01 -4.16390784e-02  9.90351625e-03 -2.43125077e-01]
 [-5.18451398e-02  1.00000000e+00 -2

In [5]:
ra = deg2rad(np.array(com1["ra"]))
dec = deg2rad(np.array(com1["dec"]))

In [6]:
com2 = radio_cat_diff_calc(icrf3k, gdr2, sou_name="iers_name")
com2

<Table length=602>
iers_name       ra_err_1       ...       nor_dec             nor_sep      
                  mas          ...                                        
   str8         float64        ...       float64             float64      
--------- -------------------- ... -------------------- ------------------
 0002+541  0.07321584713652726 ...  -1.7057350507137996  3.741251005371191
 0002-478   0.4516681517736428 ...  0.25530868283936314  1.157155702568186
 0003+380  0.05294498242586314 ...   28.548710110834488  38.90289628435303
 0003-066 0.047850566755598754 ...   -4.899226705351135  4.899592120240274
 0006+061  0.11506188429537391 ...   -8.048444496010973 12.526988769712025
 0007+106  0.04785840167457787 ...  -1.3326173658556864  5.222514755409249
 0008-264  0.07845899574871043 ...   0.7396306283617442  1.163551521194516
 0009+081   0.0753827899464934 ...   1.0714440010100013 2.3127327494862335
 0010-401  0.14923621425203867 ...  -3.1333937590297696 3.1383396481867822
      ...                  ... ...                  ...                ...
 2344-514    0.440286544231559 ...   1.0714612238507308  1.071613220122173
 2345+061  0.12088793212129043 ...  -1.4027934752069533 1.9572342386116257
 2346+385  0.05738088423364556 ...  0.04917252211901004 0.7646881955790459
 2351+456  0.06484235919660702 ...   -1.511633269435032 1.7440563463572145
 2351-154  0.05746133830379258 ...   0.4028542329878658 0.4033729802680624
 2353+816  0.05908205771265664 ... -0.47153203276963634 0.8314760619328745
 2354-021  0.10269522228975193 ... -0.32035884971222767 0.3666819345533027
 2355-106  0.06714253175753652 ...   1.1716333018221003 1.6539512612423382
 2355-534   0.1686158265281916 ...   0.5691268489057006  3.942791184906094
 2357-318  0.23529987104942013 ...  0.05241514103687193 1.4482672895770008

In [7]:
ra = deg2rad(np.array(com2["ra"]))
dec = deg2rad(np.array(com2["dec"]))

sig1, mat1 = covariance_analysis(com2["dra_err"], com2["ddec_err"], 
                                 ra, dec, 
                                 com2["dra_ddec_cov"], deg=1)

print(sig1)
print(mat1)

sig2, mat2 = covariance_analysis(com2["dra_err"], com2["ddec_err"], 
                                 ra, dec, 
                                 com2["dra_ddec_cov"], deg=2)

print(sig2)
print(mat2)

[0.00909066 0.00846458 0.00916755 0.01018809 0.00950697 0.00754858]
[[ 1.00000000e+00 -6.54797639e-03  3.74560259e-03  5.96077051e-02
  -3.87175687e-01  1.55271106e-01]
 [-6.54797639e-03  1.00000000e+00  5.80187645e-02  3.91023407e-01
   4.54747710e-02 -2.21183785e-02]
 [ 3.74560259e-03  5.80187645e-02  1.00000000e+00 -7.70656596e-02
  -3.08737753e-02 -9.52381528e-02]
 [ 5.96077051e-02  3.91023407e-01 -7.70656596e-02  1.00000000e+00
   1.40645159e-04 -9.01470344e-02]
 [-3.87175687e-01  4.54747710e-02 -3.08737753e-02  1.40645159e-04
   1.00000000e+00 -1.43384196e-01]
 [ 1.55271106e-01 -2.21183785e-02 -9.52381528e-02 -9.01470344e-02
  -1.43384196e-01  1.00000000e+00]]
[0.01056415 0.01046413 0.01035045 0.0114301  0.01100309 0.00807587
 0.00517148 0.00544264 0.01180012 0.01261795 0.0123949  0.00603196
 0.00611243 0.01234355 0.0125484  0.00964178]
[[ 1.00000000e+00 -3.32134270e-02  7.09186456e-03  5.73901187e-03
  -5.16033693e-01  1.94827606e-01 -5.13752712e-02  1.67046166e-01
   3.59993246

In [8]:
com3 = radio_cat_diff_calc(icrf3xka, gdr2, sou_name="iers_name")
com3

<Table length=505>
iers_name       ra_err_1      ...       nor_dec              nor_sep      
                  mas         ...                                         
   str8         float64       ...       float64              float64      
--------- ------------------- ... -------------------- -------------------
 0002+541 0.09003805980033948 ...   -2.946708543784513  3.0188271003830156
 0002-478 0.13552067157926384 ...  -2.3800448768777676  2.5706003622524607
 0003+380 0.05988665795370894 ...   26.889854102252066  36.632873312166744
 0003-066 0.09346512575149064 ...  0.27895921910506827  0.6518365263748636
 0006+061 0.09225816887728226 ...  -10.585329167398001   14.25564387319823
 0007+106 0.05522123270593726 ...   -2.150163484484331   5.002353007586523
 0008-264 0.12192770161551496 ...  -1.8248485446308909   2.362973609430243
 0009+081 0.07597635524116485 ...    -0.06485654271668  0.9400896290593906
 0010-401 0.12426762668082462 ...   -4.017278212951179   4.150265166797319
      ...                 ... ...                  ...                 ...
 2344-514 0.14133931542048303 ...   0.8486296244374375   1.535432461244471
 2345+061 0.15233966292037437 ...  -1.1657265388686988   1.995211022865507
 2346+385 0.05387492395144714 ...  -1.8760670848947019  3.4601742954904995
 2351+456 0.06734834415694284 ...  -1.6739256849956439  2.0459604676074603
 2351-154 0.08134325469069652 ...  -1.0998794259725604  1.3278659564628204
 2353+816 0.04952809276948208 ... -0.41973703875773616  0.5991724081940525
 2354-021 0.12353410680953035 ...  -1.2578423584758924  1.2799048674131415
 2355-106 0.05828857150368966 ...   -1.005931566422618  1.0400899396110612
 2355-534 0.12061963699470947 ...   0.1498642595505204   2.379859115701918
 2357-318 0.15235059549313076 ...   0.1412289619739691 0.27408073936430216

In [9]:
ra = deg2rad(np.array(com3["ra"]))
dec = deg2rad(np.array(com3["dec"]))

sig1, mat1 = covariance_analysis(com3["dra_err"], com3["ddec_err"], 
                                 ra, dec, 
                                 com3["dra_ddec_cov"], deg=1)

print(sig1)
print(mat1)

sig2, mat2 = covariance_analysis(com3["dra_err"], com3["ddec_err"], 
                                 ra, dec, 
                                 com3["dra_ddec_cov"], deg=2)

print(sig2)
print(mat2)

[0.00909963 0.00839187 0.00895928 0.00966408 0.00912386 0.00806742]
[[ 1.          0.02414161  0.00736998  0.08771068 -0.24357731  0.13587859]
 [ 0.02414161  1.          0.02527658  0.24205673  0.10804389  0.02186214]
 [ 0.00736998  0.02527658  1.         -0.12744906 -0.04638933 -0.17105198]
 [ 0.08771068  0.24205673 -0.12744906  1.          0.02862905 -0.10834829]
 [-0.24357731  0.10804389 -0.04638933  0.02862905  1.         -0.12292035]
 [ 0.13587859  0.02186214 -0.17105198 -0.10834829 -0.12292035  1.        ]]
[0.0098103  0.0094027  0.00943251 0.01004878 0.00964136 0.00859433
 0.00539109 0.00556036 0.0113752  0.01205273 0.01143897 0.00591844
 0.00586693 0.01146361 0.01197007 0.01012605]
[[ 1.00000000e+00 -2.89237697e-02  9.23392876e-03  4.36156546e-02
  -3.05692308e-01  1.85617269e-01 -1.79379157e-02  1.32835611e-01
   2.26892698e-01  8.47758478e-02 -6.10026284e-02 -7.24457290e-02
  -7.75358411e-02 -2.43407203e-02  1.58882674e-01 -1.68336317e-01]
 [-2.89237697e-02  1.00000000e+00  2